# Generated by Django 5.0.4 on 2025-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='educationalLevel',
            field=models.CharField(choices=[('Primary School', 'Primary School'), ('High School', 'High School'), ('Associate', 'Associate'), ('University', 'University'), ('Doctoral Student', 'Doctoral Student'), ('Magister', 'Magister'), ('Doctor', 'Doctor')], default='High School', max_length=50, verbose_name='Educational Level'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='occupation',
            field=models.CharField(max_length=50, verbose_name='Occupation'),
        ),
    ]
