# Generated by Django 5.0.4 on 2025-12-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineetraining',
            name='best_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='traineetraining',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='traineetraining',
            name='score_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='traineetraining',
            name='state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
    ]
