# Generated by Django 5.0.4 on 2025-11-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0004_block_description_en_block_description_es_and_more'),
        ('userApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('state_course', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('groups', models.ManyToManyField(to='trainingApp.group')),
            ],
        ),
        migrations.CreateModel(
            name='CourseExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exam', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('passing_score', models.IntegerField(default=70)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam', to='trainingApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.course')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'training')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='trainings',
            field=models.ManyToManyField(related_name='courses', through='trainingApp.CourseTraining', to='trainingApp.training'),
        ),
        migrations.CreateModel(
            name='ExamDeploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, null=True)),
                ('deploy_image', models.ImageField(blank=True, upload_to='trainingApp/images')),
                ('deploy_sound', models.FileField(blank=True, upload_to='trainingApp/sound')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.courseexam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100, null=True)),
                ('correct_choice', models.BooleanField(default=False)),
                ('exam_deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.examdeploy')),
            ],
        ),
        migrations.CreateModel(
            name='TraineeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Not Started', max_length=20)),
                ('current_training_index', models.PositiveIntegerField(default=0)),
                ('exam_passed', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='start date')),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.course')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.trainee')),
            ],
            options={
                'unique_together': {('trainee', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.examchoice')),
                ('exam_deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.examdeploy')),
                ('trainee_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.traineecourse')),
            ],
        ),
    ]
