# Generated by Django 5.0.4 on 2025-12-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0004_update_traineetraining_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineetraining',
            name='passing_score',
        ),
        migrations.AddField(
            model_name='training',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
    ]
