# Generated by Django 5.0.4 on 2025-11-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0005_course_courseexam_coursetraining_course_trainings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdeploy',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examchoice',
            name='exam_deploy',
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.choice'),
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='exam_deploy',
        ),
        migrations.AddField(
            model_name='course',
            name='final_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_as_final_exam', to='trainingApp.training'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='deploy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploy'),
        ),
        migrations.DeleteModel(
            name='CourseExam',
        ),
        migrations.DeleteModel(
            name='ExamChoice',
        ),
        migrations.DeleteModel(
            name='ExamDeploy',
        ),
    ]
