# Generated by Django 5.0.4 on 2026-01-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0005_remove_traineetraining_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineetraining',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traineetraining',
            name='incorrect_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
