# Generated by Django 5.0.4 on 2026-01-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0006_traineetraining_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineetraining',
            name='is_final_exam_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
