# Generated by Django 5.0.4 on 2025-11-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0006_remove_examdeploy_exam_remove_examchoice_exam_deploy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_course_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_course_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
