# Generated by Django 5.0.4 on 2025-11-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0007_course_description_en_course_description_es_and_more'),
        ('userApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='TraineeGroup',
        ),
    ]
