# Generated by Django 5.0.4 on 2026-01-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0007_traineetraining_is_final_exam_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_average_score',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Minimum average score from best training attempts required to unlock the final exam', max_digits=5),
        ),
    ]
