# Generated by Django 5.0.4 on 2025-11-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0008_rename_group_traineegroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='TrainingBlock',
        ),
    ]
