# Generated by Django 5.0.4 on 2026-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0008_course_required_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_exam_passing_score',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Minimum score required to pass the final exam', max_digits=5),
        ),
    ]
