# Generated by Django 5.0.4 on 2026-01-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0009_course_final_exam_passing_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_aditional',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='least_liked',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='more_liked',
        ),
        migrations.AddField(
            model_name='comment',
            name='course_rating',
            field=models.CharField(choices=[('very_interesting', 'Very interesting'), ('interesting', 'Interesting'), ('repetitive', 'Repetitive')], default='interesting', max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='explanations',
            field=models.CharField(choices=[('very_useful', 'Very useful and easy to understand'), ('useful_confusing', 'Useful but confusing'), ('useful_excessive', 'Useful but excessive'), ('repetitive', 'Very repetitive')], default='very_useful', max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='training_method',
            field=models.CharField(choices=[('novel', 'Novel'), ('indifferent', 'Indifferent'), ('unnecessary', 'Unnecessary')], default='novel', max_length=30),
        ),
    ]
