# Generated by Django 5.0.4 on 2025-11-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0009_rename_block_trainingblock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deploy',
            new_name='TrainingQuestion',
        ),
    ]
