# Generated by Django 5.0.4 on 2026-03-24 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0010_remove_comment_comment_aditional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingquestion',
            name='deploy_sound',
            field=models.FileField(blank=True, upload_to='trainingApp/sound', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
