# Generated by Django 5.0.4 on 2025-11-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0010_rename_deploy_trainingquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockAnswer',
            new_name='TrainingBlockAnswer',
        ),
    ]
