# Generated by Django 5.0.4 on 2025-11-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0011_rename_blockanswer_trainingblockanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeployAnswer',
            new_name='TrainingQuestionAnswer',
        ),
    ]
