# Generated by Django 5.0.4 on 2025-11-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0012_rename_deployanswer_trainingquestionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.trainingquestion'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.training'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='deploy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trainingApp.trainingquestion'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trainingApp.choice'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='trainee_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.traineecourse'),
        ),
        migrations.AlterField(
            model_name='traineetraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.training'),
        ),
        migrations.AlterField(
            model_name='trainingblock',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.training'),
        ),
        migrations.AlterField(
            model_name='trainingblockanswer',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.trainingblock'),
        ),
        migrations.AlterField(
            model_name='trainingblockanswer',
            name='trainee_Training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.traineetraining'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trainingApp.trainingblock'),
        ),
        migrations.AlterField(
            model_name='trainingquestionanswer',
            name='block_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trainingApp.trainingblockanswer'),
        ),
        migrations.AlterField(
            model_name='trainingquestionanswer',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.trainingquestion'),
        ),
        migrations.AlterField(
            model_name='trainingquestionanswer',
            name='selectedChoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.choice'),
        ),
    ]
