# Generated by Django 5.0.4 on 2025-11-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0013_alter_choice_deploy_alter_comment_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.trainingquestion'),
        ),
        migrations.AlterField(
            model_name='trainingblock',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.trainingblock'),
        ),
    ]
