# Generated by Django 5.0.4 on 2025-11-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0014_alter_choice_deploy_alter_trainingblock_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineetraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AlterField(
            model_name='trainingblockanswer',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.trainingblock'),
        ),
        migrations.AlterField(
            model_name='trainingblockanswer',
            name='trainee_Training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.traineetraining'),
        ),
        migrations.AlterField(
            model_name='trainingquestionanswer',
            name='block_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.trainingblockanswer'),
        ),
        migrations.AlterField(
            model_name='trainingquestionanswer',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.trainingquestion'),
        ),
        migrations.AlterField(
            model_name='trainingquestionanswer',
            name='selectedChoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.choice'),
        ),
    ]
