# Generated by Django 5.0.4 on 2025-11-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0015_alter_traineetraining_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='deploy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.trainingquestion'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.choice'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='trainee_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.traineecourse'),
        ),
    ]
