# Generated by Django 5.0.4 on 2025-11-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0016_alter_comment_training_alter_examanswer_deploy_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetraining',
            unique_together={('course', 'order'), ('course', 'training')},
        ),
    ]
