# Generated by Django 5.0.4 on 2025-11-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0017_alter_coursetraining_unique_together'),
        ('userApp', '0003_alter_trainee_age_alter_trainee_educationallevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineetraining',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traineecourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.course'),
        ),
        migrations.AlterField(
            model_name='traineetraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.training'),
        ),
        migrations.AlterUniqueTogether(
            name='traineetraining',
            unique_together={('trainee', 'training', 'course')},
        ),
    ]
