# Generated by Django 5.0.4 on 2025-11-30 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0018_traineetraining_course_alter_traineecourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineecourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traineetraining',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.course'),
            preserve_default=False,
        ),
    ]
