# Generated by Django 5.0.4 on 2025-11-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0019_alter_traineecourse_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traineetraining',
            unique_together=set(),
        ),
    ]
