# Generated by Django 5.0.4 on 2025-11-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0020_alter_traineetraining_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamAnswer',
        ),
    ]
